name: Spring Workflow

on: push
jobs:
  fist-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print first
        run: echo "hello ubuntu user"
      - name: Print second
        run: echo "done"
